"""HomeContent Table

Revision ID: 9db4cfe222d8
Revises: 0b5f230277de
Create Date: 2021-12-29 00:30:50.343130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db4cfe222d8'
down_revision = '0b5f230277de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homecontents',
    sa.Column('homecontentid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('homecontentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homecontents')
    # ### end Alembic commands ###
