"""column theme in HomeContent

Revision ID: e71af4aa0d4d
Revises: 9db4cfe222d8
Create Date: 2021-12-29 00:38:42.915710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71af4aa0d4d'
down_revision = '9db4cfe222d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homecontents', sa.Column('theme', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homecontents', 'theme')
    # ### end Alembic commands ###
