version: '3.8'

services:
  test_db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: wavers
      POSTGRES_PORT: 5433
    logging:
      options:
        max-size: "10m"