"""Table Admin

Revision ID: 0b5f230277de
Revises: fec31ce445b3
Create Date: 2021-12-25 03:05:40.377729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5f230277de'
down_revision = 'fec31ce445b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('adminid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('token', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('adminid')
    )
    op.drop_table('comments')
    op.drop_table('commentspost')
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.INTEGER(), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), nullable=True))
    op.create_table('commentspost',
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.commentid'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postid'], )
    )
    op.create_table('comments',
    sa.Column('commentid', sa.INTEGER(), nullable=False),
    sa.Column('commenter', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('datecreated', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.drop_table('admins')
    # ### end Alembic commands ###
