"""internacionalization

Revision ID: 218d1eef1976
Revises: 
Create Date: 2021-12-05 01:24:52.620399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218d1eef1976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('englishtitle', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('descriptionenglish', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('contentenglish', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('englishtitle', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('shortdescriptionenglish', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('bigdescriptionenglish', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'bigdescriptionenglish')
    op.drop_column('projects', 'shortdescriptionenglish')
    op.drop_column('projects', 'englishtitle')
    op.drop_column('posts', 'contentenglish')
    op.drop_column('posts', 'descriptionenglish')
    op.drop_column('posts', 'englishtitle')
    # ### end Alembic commands ###
