"""Tags relationship

Revision ID: 6e45d13908e3
Revises: 2cc81d383975
Create Date: 2021-12-04 20:43:24.438684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e45d13908e3'
down_revision = '2cc81d383975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tagid')
    )
    op.create_table('projecttags',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projectid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tagid'], )
    )
    op.create_table('tagposts',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tagid'], )
    )
    op.drop_column('posts', 'tags')
    op.drop_column('projects', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.drop_table('tagposts')
    op.drop_table('projecttags')
    op.drop_table('tags')
    # ### end Alembic commands ###
