"""Date created

Revision ID: cc7d9fb5bee6
Revises: 
Create Date: 2021-12-04 20:19:20.964370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7d9fb5bee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('datecreated', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('datecreated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'datecreated')
    op.drop_column('posts', 'datecreated')
    # ### end Alembic commands ###
