"""Table comments

Revision ID: fec31ce445b3
Revises: 218d1eef1976
Create Date: 2021-12-11 23:47:41.216524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec31ce445b3'
down_revision = '218d1eef1976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('commenter', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('datecreated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('commentspost',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.commentid'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postid'], )
    )
    op.drop_column('posts', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comments', sa.INTEGER(), nullable=True))
    op.drop_table('commentspost')
    op.drop_table('comments')
    # ### end Alembic commands ###
